server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    ##客户端默认去这个地址找注册中心
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true