server:
  port: 8081

spring:
  application:
    name: spring-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: business-service
        uri: lb://BUSINESS-SERVICE
        predicates:
          - Path=/business/**
        filters:
          - StripPrefix=1
          - RequestTime=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug