server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/caoyiqing/config
          # 仓库路径
          searchPaths: test1
          # 用户名密码
          #username: xxx
          #password: xxx
          timeout: 4
          # 跳过SSL验证
          skipSslValidation: true
          

eureka:
  instance:
    preferIpAddress: true
  client:
    ##客户端默认去这个地址找注册中心
    service-url:
      defaultZone: http://localhost:8761/eureka/