spring:
  application:
    name: business-service

server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    ##客户端默认去这个地址找注册中心
    service-url:
      defaultZone: http://localhost:8761/eureka/